Add `trusted` query param. to `incoming-transfers` endpoint
safe-global/safe-client-gateway pull request #1214
Opened 2024-02-27 12:08 UTC by iamacook

## Summary

This resolves #1206 by adding the `trusted` query param. from the `history` endpoint to the `incoming-transfers` one. The associated logic has been moved from`TransactionsHistoryMapper['mapTransfers']` into a new `TransferMapper['mapTransfers']` method that accepts an `onlyTrusted` argument.

## Changes

- A `trusted` query param to `TransactionsController['getIncomingTransfers']`
- Move trust-related filtering from `TransactionsHistoryMapper['mapTransfers']` to `TransferMapper['mapTransfers']`
- Migrate all usage of `TransferMapper['mapTransfer']` to `TransferMapper['mapTransfers']`
- Add/updated associated tests.

2024-02-28 11:01 UTC, fmrsabino requested changes

2024-02-28 11:33 UTC, iamacook commented on src/routes/transactions/transactions.service.ts
> +      (incomingTransfer) => new IncomingTransfer(incomingTransfer),
Changed in 3e8a4b2a7748e3ea848cc83e59ecd71381d4248b.

2024-02-28 11:34 UTC, iamacook commented on src/routes/transactions/mappers/transfers/transfer.mapper.spec.ts
> +          id: `${TRANSFER_PREFIX}${TRANSACTION_ID_SEPARATOR}${safe.address}${TRANSACTION_ID_SEPARATOR}${transfer.transferId}`,
I adjusted it in 3e8a4b2a7748e3ea848cc83e59ecd71381d4248b to not use `objectContaining` but still `expect.any(TrasferTransactionInfo` for the `txInfo` as that is covered by the `transfer-info.mapper.spec.ts`.

2024-02-28 11:35 UTC, iamacook commented on src/routes/transactions/__tests__/controllers/list-incoming-transfers-by-safe.transactions.controller.spec.ts
> +  it('Should filter out non-trusted ERC20 incoming transfers', async () => {
I clarified the description in 3e8a4b2a7748e3ea848cc83e59ecd71381d4248b.

2024-02-29 09:27 UTC, fmrsabino approved these changes
🚀

2024-02-29 09:32 UTC, merged