Pass Tenderly headers correctly
safe-global/safe-client-gateway pull request #1241
Opened 2024-03-04 16:32 UTC by iamacook

⚠️ Depends on #1240

## Summary

This fixes the Tenderly requests to pass the `body` and `headers` correctly.

## Changes

- Fix `addContract`/`deleteContract` network request payloads

2024-03-04 17:02 UTC, hectorgomezv requested changes

2024-03-04 17:03 UTC, iamacook commented on src/datasources/alerts-api/tenderly-api.service.ts
> +      await this.networkService.delete(url, undefined, {
I agree that it's a good addition. I will keep in mind for a follow up!

2024-03-04 17:09 UTC, hectorgomezv submitted a review, later dismissed

2024-03-05 14:13 UTC, fmrsabino commented on src/datasources/network/fetch.network.service.ts
> +  ): Promise<NetworkResponse<T>> {
Is this part of this PR 🤔 I would scope it only with the Tenderly changes.

2024-03-05 14:19 UTC, fmrsabino approved these changes
👏

2024-03-05 14:41 UTC, hectorgomezv approved these changes

2024-03-05 15:04 UTC, merged