Migrate `ProposeTransactionDto` to `zod`
safe-global/safe-client-gateway pull request #1332
Opened 2024-03-20 08:30 UTC by iamacook

## Summary

This migrates the validation of `ProposeTransactionDto` to `zod`.

## Changes

- Remove `ProposeTransactionDtoValidationPipe` and associated schemas.
- Add test-covered `ProposeTransactionDtoSchema` and infer types from it.
- Propagate type requirements.
- Update tests accordingly.

2024-03-20 08:41 UTC, iamacook commented on src/routes/transactions/__tests__/controllers/propose-transaction.transactions.controller.spec.ts
> +      .compile();
This change was required in order to test validation.

2024-03-21 14:16 UTC, fmrsabino requested changes

2024-03-21 14:16 UTC, fmrsabino commented on src/routes/transactions/entities/schemas/propose-transaction.dto.schema.ts
> +export const ProposeTransactionDtoSchema = z.object({
The payload is missing the `origin`

2024-03-21 16:31 UTC, hectorgomezv approved these changes

2024-03-22 09:27 UTC, fmrsabino approved these changes

2024-03-22 09:37 UTC, merged